# Generated by Django 5.2.3 on 2025-09-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toman', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('dollor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pounds', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
