# Generated by Django 5.2.6 on 2025-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toman', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('dollor', models.DecimalField(decimal_places=2, default=115, max_digits=8)),
                ('pounds', models.DecimalField(decimal_places=2, default=155, max_digits=8)),
                ('euro', models.DecimalField(decimal_places=2, default=135, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='pounds',
            new_name='pound',
        ),
        migrations.AddField(
            model_name='wallet',
            name='euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
