# Generated by Django 5.2.6 on 2025-10-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_price_rename_pounds_wallet_pound_wallet_euro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='euro',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='euro',
        ),
    ]
