# Generated by Django 5.2.6 on 2025-10-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_price_euro_remove_wallet_euro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='dollor',
            new_name='dollar',
        ),
    ]
