# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_dollor_wallet_dollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='dollor',
            new_name='dollar',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='pounds',
            new_name='pound',
        ),
    ]
