# Generated by Django 4.2.18 on 2025-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Order',
        ),
    ]
